# Generated by Django 5.2.4 on 2025-07-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillrequest',
            name='seen_by_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
